import { Collection } from '@x/models/dist'

export default function useTwelvefoldCollection(): Collection {
  return {
    holdingCount: 0,
    isInternal: false,
    isOwnerble: false,
    chainId: 0,
    erc721Address: '',
    tokenType: 721,
    owner: '',
    email: '',
    collectionName: 'TwelveFold',
    description:
      'TwelveFold by Yuga Labs - 300 unique generative art pieces, inscribed onto satoshis on the Bitcoin blockchain.',
    categories: [],
    logoImageHash: '',
    logoImageUrl: 'https://storage.x.xyz/twelvefold/TwelveFold_1.webp',
    coverImageHash: '',
    coverImageUrl: '',
    siteUrl: '',
    discord: '',
    twitterHandle: '',
    instagramHandle: '',
    mediumHandle: '',
    telegram: '',
    isVerified: false,
    royalty: 0,
    feeRecipient: '',
    isRegistered: true,
    supply: 300,
    attributes: {
      Series: {
        '1': 12,
        '2': 12,
        '3': 12,
        '4': 12,
        '5': 12,
        '6': 12,
        '7': 12,
        '8': 12,
        '9': 12,
        '10': 12,
        '11': 12,
        '12': 12,
        '13': 12,
        '14': 12,
        '15': 12,
        '16': 12,
        '17': 12,
        '18': 12,
        '19': 12,
        '20': 12,
        '21': 12,
        '22': 12,
        '23': 12,
        '24': 12,
        '25': 12,
      },
      Season: {
        Spring: 72,
        Summer: 84,
        Autumn: 72,
        Winter: 72,
      },
    },
    numOwners: 0,
    numOwnersMovement: 0,
    floorPrice: 0,
    openseaFloorPriceInNative: 0,
    openseaFloorPriceInUsd: 0,
    openseaFloorPriceMovement: 0,
    usdFloorPrice: 0,
    floorPriceMovement: 0,
    hasFloorPrice: false,
    highestSale: 0,
    highestSaleInUsd: 0,
    lastSoldAt: '2022-11-22T03:45:11Z',
    hasBeenSold: 0,
    lastListedAt: '2022-06-21T01:45:16Z',
    hasBeenListed: 0,
    openseaSalesVolume: 0,
    openseaSalesVolumeChange: 0,
    openseaFloorPriceInApe: 0,
  }
}
